name: aura_mood_flutter
description: A beautiful mood tracking app with animated aura backgrounds.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  provider: ^6.1.1
  flutter_hooks: ^0.20.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  confetti: ^0.7.0
  audioplayers: ^5.2.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/ 